name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Building package
      run: mvn clean package
    - name: tests
      run: ls

