name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Package
      run: mvn clean package

    - name: Finding Artifact
      run : find / -name "*.jar" -type f -exec file {} \; | grep -i ".*:.*Java archive data.*"
      
    - name: Finding Artifact
      run: cp target/TowerDefense.jar ${{ github.workspace }}/TowerDefense.jar
